import {Region} from "../models/region.model";

export const regions: Region[] = [
  {
    name: 'Europe West',
    shorthand: 'euw',
    code: 'euw1',
    majorRegion: 'europe',
    leaderboardRegion: true
  },
  {
    name: 'Europe Nordic & East',
    shorthand: 'eune',
    code: 'eun1',
    majorRegion: 'europe',
    leaderboardRegion: true
  },
  {
    name: 'North America',
    shorthand: 'na',
    code: 'na1',
    majorRegion: 'americas',
    leaderboardRegion: true
  },
  {
    name: 'Oceania',
    shorthand: 'oce',
    code: 'oc1',
    majorRegion: 'americas',
    leaderboardRegion: true
  },
  {
    name: 'Korea',
    shorthand: 'kr',
    code: 'kr',
    majorRegion: 'asia',
    leaderboardRegion: true
  },
  {
    name: 'Japan',
    shorthand: 'jp',
    code: 'jp1',
    majorRegion: 'asia',
    leaderboardRegion: true
  },
  {
    name: 'Brazil',
    shorthand: 'br',
    code: 'br1',
    majorRegion: 'americas',
    leaderboardRegion: true
  },
  {
    name: 'LAS',
    shorthand: 'las',
    code: 'la2',
    majorRegion: 'americas',
    leaderboardRegion: true
  },
  {
    name: 'LAN',
    shorthand: 'lan',
    code: 'la1',
    majorRegion: 'americas',
    leaderboardRegion: true
  },
  {
    name: 'Russia',
    shorthand: 'ru',
    code: 'ru',
    majorRegion: 'europe',
    leaderboardRegion: true
  },
  {
    name: 'Türkiye',
    shorthand: 'tr',
    code: 'tr1',
    majorRegion: 'europe',
    leaderboardRegion: true
  },
  {
    name: 'Singapore',
    shorthand: 'sg',
    code: 'sg',
    majorRegion: 'asia',
    leaderboardRegion: false
  },
  {
    name: 'Philippines',
    shorthand: 'ph',
    code: 'ph',
    majorRegion: 'asia',
    leaderboardRegion: false
  },
  {
    name: 'Taiwan',
    shorthand: 'tw',
    code: 'tw',
    majorRegion: 'asia',
    leaderboardRegion: false
  },
  {
    name: 'Vietnam',
    shorthand: 'vn',
    code: 'vn',
    majorRegion: 'asia',
    leaderboardRegion: false
  },
  {
    name: 'Thailand',
    shorthand: 'th',
    code: 'th',
    majorRegion: 'asia',
    leaderboardRegion: false
  }];

export const champions: {
  [key: string]: string;
} = {
  "266": "Aatrox",
  "103": "Ahri",
  "84": "Akali",
  "166": "Akshan",
  "12": "Alistar",
  "32": "Amumu",
  "34": "Anivia",
  "1": "Annie",
  "523": "Aphelios",
  "22": "Ashe",
  "136": "AurelionSol",
  "268": "Azir",
  "432": "Bard",
  "200": "Belveth",
  "53": "Blitzcrank",
  "63": "Brand",
  "201": "Braum",
  "51": "Caitlyn",
  "164": "Camille",
  "69": "Cassiopeia",
  "31": "Chogath",
  "42": "Corki",
  "122": "Darius",
  "131": "Diana",
  "119": "Draven",
  "36": "DrMundo",
  "245": "Ekko",
  "60": "Elise",
  "28": "Evelynn",
  "81": "Ezreal",
  "9": "Fiddlesticks",
  "114": "Fiora",
  "105": "Fizz",
  "3": "Galio",
  "41": "Gangplank",
  "86": "Garen",
  "150": "Gnar",
  "79": "Gragas",
  "104": "Graves",
  "887": "Gwen",
  "120": "Hecarim",
  "74": "Heimerdinger",
  "420": "Illaoi",
  "39": "Irelia",
  "427": "Ivern",
  "40": "Janna",
  "59": "JarvanIV",
  "24": "Jax",
  "126": "Jayce",
  "202": "Jhin",
  "222": "Jinx",
  "145": "Kaisa",
  "429": "Kalista",
  "43": "Karma",
  "30": "Karthus",
  "38": "Kassadin",
  "55": "Katarina",
  "10": "Kayle",
  "141": "Kayn",
  "85": "Kennen",
  "121": "Khazix",
  "203": "Kindred",
  "240": "Kled",
  "96": "KogMaw",
  "897": "KSante",
  "7": "Leblanc",
  "64": "LeeSin",
  "89": "Leona",
  "876": "Lillia",
  "127": "Lissandra",
  "236": "Lucian",
  "117": "Lulu",
  "99": "Lux",
  "54": "Malphite",
  "90": "Malzahar",
  "57": "Maokai",
  "11": "MasterYi",
  "21": "MissFortune",
  "62": "MonkeyKing",
  "82": "Mordekaiser",
  "25": "Morgana",
  "267": "Nami",
  "75": "Nasus",
  "111": "Nautilus",
  "518": "Neeko",
  "76": "Nidalee",
  "895": "Nilah",
  "56": "Nocturne",
  "20": "Nunu",
  "2": "Olaf",
  "61": "Orianna",
  "516": "Ornn",
  "80": "Pantheon",
  "78": "Poppy",
  "555": "Pyke",
  "246": "Qiyana",
  "133": "Quinn",
  "497": "Rakan",
  "33": "Rammus",
  "421": "RekSai",
  "526": "Rell",
  "888": "Renata",
  "58": "Renekton",
  "107": "Rengar",
  "92": "Riven",
  "68": "Rumble",
  "13": "Ryze",
  "360": "Samira",
  "113": "Sejuani",
  "235": "Senna",
  "147": "Seraphine",
  "875": "Sett",
  "35": "Shaco",
  "98": "Shen",
  "102": "Shyvana",
  "27": "Singed",
  "14": "Sion",
  "15": "Sivir",
  "72": "Skarner",
  "37": "Sona",
  "16": "Soraka",
  "50": "Swain",
  "517": "Sylas",
  "134": "Syndra",
  "223": "TahmKench",
  "163": "Taliyah",
  "91": "Talon",
  "44": "Taric",
  "17": "Teemo",
  "412": "Thresh",
  "18": "Tristana",
  "48": "Trundle",
  "23": "Tryndamere",
  "4": "TwistedFate",
  "29": "Twitch",
  "77": "Udyr",
  "6": "Urgot",
  "110": "Varus",
  "67": "Vayne",
  "45": "Veigar",
  "161": "Velkoz",
  "711": "Vex",
  "254": "Vi",
  "234": "Viego",
  "112": "Viktor",
  "8": "Vladimir",
  "106": "Volibear",
  "19": "Warwick",
  "498": "Xayah",
  "101": "Xerath",
  "5": "XinZhao",
  "157": "Yasuo",
  "777": "Yone",
  "83": "Yorick",
  "350": "Yuumi",
  "154": "Zac",
  "238": "Zed",
  "221": "Zeri",
  "115": "Ziggs",
  "26": "Zilean",
  "142": "Zoe",
  "143": "Zyra",
};

export const queueIdArray = [
  {
    queueId: 0,
    map: "Custom games",
    description: null,
    notes: null,
  },
  {
    queueId: 72,
    map: "Howling Abyss",
    description: "1v1 ARAM",
    notes: null,
  },
  {
    queueId: 73,
    map: "Howling Abyss",
    description: "2v2 ARAM",
    notes: null,
  },
  {
    queueId: 75,
    map: "Summoner's Rift",
    description: "6v6 Hexakill games",
    notes: null,
  },
  {
    queueId: 76,
    map: "Summoner's Rift",
    description: "URF",
    notes: null,
  },
  {
    queueId: 78,
    map: "Howling Abyss",
    description: "One For All",
    notes: null,
  },
  {
    queueId: 83,
    map: "Summoner's Rift",
    description: "Co-op vs URF",
    notes: null,
  },
  {
    queueId: 100,
    map: "Butcher's Bridge",
    description: "ARAM",
    notes: null,
  },
  {
    queueId: 310,
    map: "Summoner's Rift",
    description: "Nemesis",
    notes: null,
  },
  {
    queueId: 313,
    map: "Summoner's Rift",
    description: "Black Market Brawlers games",
    notes: null,
  },
  {
    queueId: 317,
    map: "Crystal Scar",
    description: "Definitely Not Dominion games",
    notes: null,
  },
  {
    queueId: 325,
    map: "Summoner's Rift",
    description: "All Random",
    notes: null,
  },
  {
    queueId: 400,
    map: "Summoner's Rift",
    description: "Normal Draft",
    notes: null,
  },
  {
    queueId: 420,
    map: "Summoner's Rift",
    description: "Ranked Solo",
    notes: null,
  },
  {
    queueId: 430,
    map: "Summoner's Rift",
    description: "Normal blind",
    notes: null,
  },
  {
    queueId: 440,
    map: "Summoner's Rift",
    description: "Ranked Flex",
    notes: null,
  },
  {
    queueId: 450,
    map: "Howling Abyss",
    description: "ARAM",
    notes: null,
  },
  {
    queueId: 460,
    map: "Twisted Treeline",
    description: "3v3 Blind",
    notes: "Deprecated in patch 9.23",
  },
  {
    queueId: 470,
    map: "Twisted Treeline",
    description: "3v3 Ranked Flex",
    notes: "Deprecated in patch 9.23",
  },
  {
    queueId: 600,
    map: "Summoner's Rift",
    description: "Blood Hunt Assassin games",
    notes: null,
  },
  {
    queueId: 610,
    map: "Cosmic Ruins",
    description: "Dark Star: Singularity games",
    notes: null,
  },
  {
    queueId: 700,
    map: "Summoner's Rift",
    description: "Clash",
    notes: null,
  },
  {
    queueId: 820,
    map: "Twisted Treeline",
    description: "Co-op Beginner",
    notes: null,
  },
  {
    queueId: 830,
    map: "Summoner's Rift",
    description: "Co-op Intro",
    notes: null,
  },
  {
    queueId: 840,
    map: "Summoner's Rift",
    description: "Co-op Beginner",
    notes: null,
  },
  {
    queueId: 850,
    map: "Summoner's Rift",
    description: "Co-op Intermediate",
    notes: null,
  },
  {
    queueId: 900,
    map: "Summoner's Rift",
    description: "ARURF",
    notes: null,
  },
  {
    queueId: 910,
    map: "Crystal Scar",
    description: "Ascension",
    notes: null,
  },
  {
    queueId: 920,
    map: "Howling Abyss",
    description: "Legend of the Poro King",
    notes: null,
  },
  {
    queueId: 940,
    map: "Summoner's Rift",
    description: "Nexus Siege",
    notes: null,
  },
  {
    queueId: 950,
    map: "Summoner's Rift",
    description: "Doom Bots Voting",
    notes: null,
  },
  {
    queueId: 960,
    map: "Summoner's Rift",
    description: "Doom Bots Standard",
    notes: null,
  },
  {
    queueId: 980,
    map: "Valoran City Park",
    description: "Star Guardian Invasion: Normal games",
    notes: null,
  },
  {
    queueId: 990,
    map: "Valoran City Park",
    description: "Star Guardian Invasion: Onslaught games",
    notes: null,
  },
  {
    queueId: 1000,
    map: "Overcharge",
    description: "PROJECT: Hunters",
    notes: null,
  },
  {
    queueId: 1010,
    map: "Summoner's Rift",
    description: "Snow ARURF",
    notes: null,
  },
  {
    queueId: 1020,
    map: "Summoner's Rift",
    description: "One for All",
    notes: null,
  },
  {
    queueId: 1030,
    map: "Crash Site",
    description: "Odyssey Extraction: Intro games",
    notes: null,
  },
  {
    queueId: 1040,
    map: "Crash Site",
    description: "Odyssey Extraction: Cadet games",
    notes: null,
  },
  {
    queueId: 1050,
    map: "Crash Site",
    description: "Odyssey Extraction: Crewmember games",
    notes: null,
  },
  {
    queueId: 1060,
    map: "Crash Site",
    description: "Odyssey Extraction: Captain games",
    notes: null,
  },
  {
    queueId: 1070,
    map: "Crash Site",
    description: "Odyssey Extraction: Onslaught games",
    notes: null,
  },
  {
    queueId: 1090,
    map: "Convergence",
    description: "TFT",
    notes: null,
  },
  {
    queueId: 1100,
    map: "Convergence",
    description: "Ranked TFT",
    notes: null,
  },
  {
    queueId: 1110,
    map: "Convergence",
    description: "TFT Tutorial",
    notes: null,
  },
  {
    queueId: 1111,
    map: "Convergence",
    description: "TFT Test",
    notes: null,
  },
  {
    queueId: 1300,
    map: "Nexus Blitz",
    description: "Nexus Blitz",
    notes: null,
  },
  {
    queueId: 1400,
    map: "Summoner's Rift",
    description: "Ultimate Spellbook",
    notes: null,
  },
  {
    queueId: 1700,
    map: null,
    description: "Arena",
    notes: null
  },
  {
    queueId: 1900,
    map: "Summoner's Rift",
    description: "URF",
    notes: null,
  },
  {
    queueId: 2000,
    map: "Summoner's Rift",
    description: "Tutorial 1",
    notes: null,
  },
  {
    queueId: 2010,
    map: "Summoner's Rift",
    description: "Tutorial 2",
    notes: null,
  },
  {
    queueId: 2020,
    map: "Summoner's Rift",
    description: "Tutorial 3",
    notes: null,
  },
];

export const summonerSpell: {
  [key: string]: string;
} = {
  "21": "SummonerBarrier.png",
  "1": "SummonerBoost.png",
  "14": "SummonerDot.png",
  "3": "SummonerExhaust.png",
  "4": "SummonerFlash.png",
  "6": "SummonerHaste.png",
  "7": "SummonerHeal.png",
  "13": "SummonerMana.png",
  "30": "SummonerPoroRecall.png",
  "31": "SummonerPoroThrow.png",
  "11": "SummonerSmite.png ",
  "39": "SummonerSnowball.png",
  "32": "SummonerSnowURFSnowball_Mark.png",
  "12": "SummonerTeleport.png ",
  "54": "Summoner_UltBookPlaceholder.png",
  "55": "Summoner_UltBookSmitePlaceholder.png",
};

export const runes: {
  [key: string]: string;
} = {
  "2202": "ShrinkRay",


  "8100": "Styles/7200_Domination.png",
  "8300": "Styles/7203_Whimsy.png",
  "8000": "Styles/7201_Precision.png",
  "8400": "Styles/7204_Resolve.png",
  "8200": "Styles/7202_Sorcery.png",

  "8112": "Styles/Domination/Electrocute/Electrocute.png",
  "8124": "Styles/Domination/Predator/Predator.png",
  "8128": "Styles/Domination/DarkHarvest/DarkHarvest.png",
  "9923": "Styles/Domination/HailOfBlades/HailOfBlades.png",

  "8351": "Styles/Inspiration/GlacialAugment/GlacialAugment.png",
  "8360": "Styles/Inspiration/UnsealedSpellbook/UnsealedSpellbook.png",
  "8369": "Styles/Inspiration/FirstStrike/FirstStrike.png",

  "8005": "Styles/Precision/PressTheAttack/PressTheAttack.png",
  "8008": "Styles/Precision/LethalTempo/LethalTempoTemp.png",
  "8021": "Styles/Precision/FleetFootwork/FleetFootwork.png",
  "8010": "Styles/Precision/Conqueror/Conqueror.png",

  "8437": "Styles/Resolve/GraspOfTheUndying/GraspOfTheUndying.png",
  "8439": "Styles/Resolve/VeteranAftershock/VeteranAftershock.png",
  "8465": "Styles/Resolve/Guardian/Guardian.png",

  "8214": "Styles/Sorcery/SummonAery/SummonAery.png",
  "8229": "Styles/Sorcery/ArcaneComet/ArcaneComet.png",
  "8230": "Styles/Sorcery/PhaseRush/PhaseRush.png",
};

export const leagues = {
  "LEC": 4190,
  "LCS": 4191,
  "LCK": 4188,
  "LPL": 4192,
};
